# ingles.py

t = {
    # General
    "grid": "Grid",
    "list": "List",
    "totals": "Totals:",
    "new": "New",
    "learn": "Lrn",
    "review": "Due",
    "unpin_from_top": "Unpin from top",
    "pin_to_top": "Pin to top",
    "set_cover_image": "Cover Image (Grid)",
    "set_image": "Set Image",
    "remove_image": "Remove Image",
    "cover_set_success": "Cover set successfully!",
    "cover_removed": "Cover removed.",
    "choose_cover_image": "Choose Cover Image",
    "images": "Images",
    "set_background_color": "Set Background Color",
    "default": "Default",
    "red": "Red",
    "green": "Green",
    "blue": "Blue",
    "yellow": "Yellow",
    "purple": "Purple",
    "customize_columns": "Customize Columns (Pinned)",
    "show_all_columns": "Show All Columns",
    "restore_previous_view": "Restore Previous View",

    # Column Titles and Tooltips
    "col_progress_bar": "Progress Bar",
    "col_estimated_time": "Estimated Time",
    "col_avg_time": "Avg Time (s/card)",
    "col_speed": "Speed (c/min)",
    "col_daily_goal": "Daily Goal",
    "col_retention_today": "Retention Today",
    "col_ease": "Difficulty (Ease)",
    "col_leeches": "Leeches",
    "col_tomorrow_forecast": "Tomorrow's Forecast",
    "col_total_cards": "Total Cards",
    "col_streak_count": "Streak (Qty)",
    "col_streak_pct": "Streak (%)",
    "daily_goal_tooltip": "Daily Goal",
    "total_goals_hit_history": "Total goals met in history",
    "deck_hp": "Deck HP",
    "leech_tooltip": "Leeches (cards with {count}+ lapses)",
    "tomorrow_tooltip": "Tomorrow",
    "total_tooltip": "Total",
    "streak_count_tooltip": "Cards with a streak of {count}+ consecutive correct answers",
    "streak_pct_tooltip": "Percentage of cards with a streak of correct answers",
    "estimated_time_tooltip": "Estimated Time to finish",
    "avg_seconds_per_card": "Average seconds per card",
    "speed_tooltip": "Speed (Cards per minute)",
    "daily_goal_reviews_tooltip": "Daily Review Goal",
    "retention_rate_today": "Retention Rate (Correct answers) Today",
    "avg_ease_tooltip": "Average Ease",
    "leeches_tooltip_long": "Leeches (threshold: {count}+ lapses)",
    "cards_scheduled_for_tomorrow": "Cards scheduled for Tomorrow",
    "total_cards_in_deck": "Total Cards in Deck",
    "mature_cards_count": "Cards with a streak of {count}+ consecutive correct answers",
    "mature_cards_pct": "Cards with streak (%)",
    "sort_by_name": "Sort by Name",
    "sort_by_count": "Sort by Count",
    "click_to_sort": "Click to sort",
    "move_left": "Move left",
    "move_right": "Move right",

    # Main Header
    "pinned_decks_report": "Pinned Decks Report",
    "pinned_decks_title": "Pinned Decks",
    "today_answers": "Today's answers: Again / Hard / Good / Easy",
    "last_review_time_label": "Last review:",
    "global_streak_label": "{day} day streak",
    "toggle_list_view": "Switch to List",
    "toggle_grid_view": "Switch to Grid",
    "generate_html_report": "Generate HTML Report",
    "hide_default_deck_list": "Hide default deck list",
    "show_default_deck_list": "Show default deck list",
    "lang_pt": "Switch to Portuguese",
    "lang_en": "Switch to English",

    # RPG
    "level": "Lvl",
    "max_level_reached": "Maximum Level Reached!",
    "global_progress": "Global Progress",
    "level_0_name": "🧹 Villager",
    "level_1_name": "🛡️ Recruit",
    "level_2_name": "⚔️ Soldier",
    "level_3_name": "🎖️ Veteran",
    "level_4_name": "🦅 Elite",
    "level_5_name": "🧙 Master",
    "level_6_name": "👑 Grandmaster",
    "level_7_name": "🐲 LEGEND",
    "level_cursed": "💀 Cursed",

    # New Deck Icon Titles
    "rpg_icon_level_0": "Newbie",
    "rpg_icon_level_1": "Beginner",
    "rpg_icon_level_2": "Practitioner",
    "rpg_icon_level_3": "Student",
    "rpg_icon_level_4": "Dedicated",
    "rpg_icon_level_5": "Experienced",
    "rpg_icon_level_6": "Proficient",
    "rpg_icon_level_7": "Specialist",
    "rpg_icon_level_8": "Master",
    "rpg_icon_level_9": "Legend",

    # HTML Report
    "html_report_title": "Anki Report",
    "deck_progress_tooltip": "{deck_name} • Progress: {pct}% ({done}/{total})",

    # Custom Study
    "study_button": "Study",
    "study_selected_decks": "Study {count} selected decks",
    "select_for_study": "Select for group study",
    "no_decks_selected": "No decks selected.",
    "starting_study_for_decks": "Starting study for {count} decks...",
    "temp_deck_name": "Custom Study (Temporary)",

    # Others
    "no_pinned_decks": "Click the gear icon ⚙ next to a deck to pin it",

    # --- NEW (Charts) ---
    "chart_days_label": "Chart Days",
    "show_hide_charts": "Show/Hide Charts",
    "daily_summary_chart_title": "Daily Summary",
    "cards": "Cards",
    "chart_title_retention": "Retention ({days} days)",
    "chart_title_reviews": "Reviews ({days} days)",
    "chart_title_ease": "Avg Ease ({days} days)",
    "chart_title_activity": "Activity History ({days} days)",
}