# portugues.py

t = {
    # Geral
    "grid": "Grade",
    "list": "Lista",
    "totals": "Totais:",
    "new": "Novos",
    "learn": "Apr.",
    "review": "Rev.",
    "unpin_from_top": "Desafixar do topo",
    "pin_to_top": "Fixar no topo",
    "set_cover_image": "Imagem de Capa (Grid)",
    "set_image": "Definir Imagem",
    "remove_image": "Remover Imagem",
    "cover_set_success": "Capa definida com sucesso!",
    "cover_removed": "Capa removida.",
    "choose_cover_image": "Escolher Imagem de Capa",
    "images": "Imagens",
    "set_background_color": "Definir Cor de Fundo",
    "default": "Padrão",
    "red": "Vermelho",
    "green": "Verde",
    "blue": "Azul",
    "yellow": "Amarelo",
    "purple": "Roxo",
    "customize_columns": "Personalizar Colunas (Pinned)",
    "show_all_columns": "Mostrar Todas as Colunas",
    "restore_previous_view": "Restaurar Visualização Anterior",

    # Títulos das Colunas e Tooltips
    "col_progress_bar": "Barra de Progresso",
    "col_estimated_time": "Tempo Estimado",
    "col_avg_time": "Média Tempo (s/card)",
    "col_speed": "Velocidade (c/min)",
    "col_daily_goal": "Meta Diária",
    "col_retention_today": "Retenção Hoje",
    "col_ease": "Dificuldade (Ease)",
    "col_leeches": "Sanguessugas",
    "col_tomorrow_forecast": "Previsão Amanhã",
    "col_total_cards": "Total de Cards",
    "col_streak_count": "Streak (Qtd)",
    "col_streak_pct": "Streak (%)",
    "daily_goal_tooltip": "Meta Diária",
    "total_goals_hit_history": "Total de metas batidas na história",
    "deck_hp": "HP do Deck",
    "leech_tooltip": "Sanguessugas (cartões com {count}+ erros)",
    "tomorrow_tooltip": "Amanhã",
    "total_tooltip": "Total",
    "streak_count_tooltip": "Cartões com sequência de {count}+ acertos seguidos",
    "streak_pct_tooltip": "Porcentagem de cartões com sequência de acertos",
    "estimated_time_tooltip": "Tempo Estimado para finalizar",
    "avg_seconds_per_card": "Média de segundos por carta",
    "speed_tooltip": "Velocidade (Cartas por minuto)",
    "daily_goal_reviews_tooltip": "Meta Diária de Revisões",
    "retention_rate_today": "Taxa de Retenção (Acertos) Hoje",
    "avg_ease_tooltip": "Facilidade Média (Ease)",
    "leeches_tooltip_long": "Sanguessugas (limite: {count}+ erros)",
    "cards_scheduled_for_tomorrow": "Cartas agendadas para Amanhã",
    "total_cards_in_deck": "Total de Cartas no Deck",
    "mature_cards_count": "Cartas com sequência de {count}+ acertos seguidos",
    "mature_cards_pct": "Cartas com sequência de acertos (%)",
    "sort_by_name": "Ordenar por Nome",
    "sort_by_count": "Ordenar por Quantidade",
    "click_to_sort": "Clique para ordenar",
    "move_left": "Mover para esquerda",
    "move_right": "Mover para direita",

    # Cabeçalho Principal
    "pinned_decks_report": "Relatório de Decks Fixados",
    "pinned_decks_title": "Decks Fixados",
    "today_answers": "Respostas de hoje: Errei / Difícil / Bom / Fácil",
    "last_review_time_label": "Última rev:",
    "global_streak_label": "{day} dias seguidos",
    "toggle_list_view": "Alternar para Lista",
    "toggle_grid_view": "Alternar para Grade",
    "generate_html_report": "Gerar Relatório HTML",
    "hide_default_deck_list": "Ocultar lista de decks padrão",
    "show_default_deck_list": "Mostrar lista de decks padrão",
    "lang_pt": "Mudar para Português",
    "lang_en": "Mudar para Inglês",

    # RPG
    "level": "Nvl",
    "max_level_reached": "Nível Máximo Alcançado!",
    "global_progress": "Progresso Global",
    "level_0_name": "🧹 Aldeão",
    "level_1_name": "🛡️ Recruta",
    "level_2_name": "⚔️ Soldado",
    "level_3_name": "🎖️ Veterano",
    "level_4_name": "🦅 Elite",
    "level_5_name": "🧙 Mestre",
    "level_6_name": "👑 Grão-Mestre",
    "level_7_name": "🐲 LENDA",
    "level_cursed": "💀 Amaldiçoado",
    
    # Novos Títulos dos Ícones de Deck
    "rpg_icon_level_0": "Novato",
    "rpg_icon_level_1": "Iniciante",
    "rpg_icon_level_2": "Praticante",
    "rpg_icon_level_3": "Estudante",
    "rpg_icon_level_4": "Dedicado",
    "rpg_icon_level_5": "Experiente",
    "rpg_icon_level_6": "Proficiente",
    "rpg_icon_level_7": "Especialista",
    "rpg_icon_level_8": "Mestre",
    "rpg_icon_level_9": "Lenda",

    # Relatório HTML
    "html_report_title": "Relatório Anki",
    "deck_progress_tooltip": "{deck_name} • Progresso: {pct}% ({done}/{total})",

    # Estudo Personalizado
    "study_button": "Estudar",
    "study_selected_decks": "Estudar {count} baralhos selecionados",
    "select_for_study": "Selecionar para estudo em grupo",
    "no_decks_selected": "Nenhum baralho selecionado.",
    "starting_study_for_decks": "Iniciando estudo de {count} baralhos...",
    "temp_deck_name": "Estudo Personalizado (Temporário)",

    # Outros
    "no_pinned_decks": "Clique na engrenagem ⚙ ao lado do deck e fixar",

    # --- NOVOS (Gráficos) ---
    "chart_days_label": "Dias Gráfico",
    "show_hide_charts": "Mostrar/Ocultar Gráficos",
    "daily_summary_chart_title": "Resumo Diário",
    "cards": "Cards",
    "chart_title_retention": "Retenção ({days} dias)",
    "chart_title_reviews": "Revisões ({days} dias)",
    "chart_title_ease": "Ease Médio ({days} dias)",
    "chart_title_activity": "Histórico de Atividade ({days} dias)",
}